export const buttonList = [
  { label: 'AC', value: 'AC', type: 'clear', theme: 'light', position: 'top-left' },
  { label: 'plusOrMinus', value: '\u00b1', type: 'plusOrMinus', theme: 'light', position: 'top' },
  { label: 'percentage', value: '\u0025', type: 'percentage', theme: 'light', position: 'top' },
  { label: 'division', value: '\u00f7', type: 'operator', theme: 'bright', position: 'top-right' },
  { label: 'seven', value: '\u0037', type: 'number', theme: 'dark', position: 'left' },
  { label: 'eight', value: '\u0038', type: 'number', theme: 'dark' },
  { label: 'nine', value: '\u0039', type: 'number', theme: 'dark' },
  { label: 'multiplication', value: '\u00d7', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'four', value: '\u0034', type: 'number', theme: 'dark', position: 'left' },
  { label: 'five', value: '\u0035', type: 'number', theme: 'dark' },
  { label: 'six', value: '\u0036', type: 'number', theme: 'dark' },
  { label: 'subtraction', value: '\u002d', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'one', value: '\u0031', type: 'number', theme: 'dark', position: 'left' },
  { label: 'two', value: '\u0032', type: 'number', theme: 'dark' },
  { label: 'three', value: '\u0033', type: 'number', theme: 'dark' },
  { label: 'addition', value: '\u002b', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'zero', value: '\u0030', type: 'number', theme: 'dark', position: 'bottom-left', doubleSpace: true },
  { label: 'dot', value: '\u22c5', type: 'decimal', theme: 'dark', position: 'bottom' },
  { label: 'equation', value: '\u003d', type: 'assignment', theme: 'bright', position: 'bottom-right' },
]