export const buttonList = [
  { label: 'AC', value: 'AC', type: 'clear', theme: 'light', position: 'top-left' },
  { label: 'plusOrMinus', value: '\u00b1', type: 'plusOrMinus', theme: 'light', position: 'top' },
  { label: 'percentage', value: '\u0025', type: 'percentage', theme: 'light', position: 'top' },
  { label: 'division', value: '\u00f7', type: 'operator', theme: 'bright', position: 'top-right' },
  { label: 'seven', value: 7, type: 'number', theme: 'dark', position: 'left' },
  { label: 'eight', value: 8, type: 'number', theme: 'dark' },
  { label: 'nine', value: 9, type: 'number', theme: 'dark' },
  { label: 'multiplication', value: '\u00d7', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'four', value: 4, type: 'number', theme: 'dark', position: 'left' },
  { label: 'five', value: 5, type: 'number', theme: 'dark' },
  { label: 'six', value: 6, type: 'number', theme: 'dark' },
  { label: 'subtraction', value: '\u002d', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'one', value: 1, type: 'number', theme: 'dark', position: 'left' },
  { label: 'two', value: 2, type: 'number', theme: 'dark' },
  { label: 'three', value: 3, type: 'number', theme: 'dark' },
  { label: 'addition', value: '\u002b', type: 'operator', theme: 'bright', position: 'right' },
  { label: 'zero', value: 0, type: 'number', theme: 'dark', position: 'bottom-left', doubleSpace: true },
  { label: 'dot', value: '.', type: 'decimal', theme: 'dark', position: 'bottom' },
  { label: 'equation', value: '\u003d', type: 'assignment', theme: 'bright', position: 'bottom-right' },
]